spring:
    datasource:
        url: ${SPRING_CART_DATASOURCE_URL:jdbc:mysql://localhost:3306/cart}
        username: ${SPRING_CART_DATASOURCE_USERNAME:root}
        password: ${SPRING_CART_DATASOURCE_PASSWORD:password}
        hikari:
            schema: ${SPRING_CART_DATASOURCE_SCHEME:cart}

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

    mvc:
        log-request-details: true



logging:
    level:
        web: trace
        org:
            springframework:
                web: trace

server:
    port: 8093

allowed-origins:
    http://localhost:3000/,
    *,

emazon:
    stock:
        base-url: localhost:8091
    user:
        base-url: localhost:8090
    transaction:
        base-url: localhost:8092