spring:
    datasource:
        url: ${SPRING_CART_DATASOURCE_URL:jdbc:mysql://localhost:3306/cart}
        username: ${SPRING_CART_DATASOURCE_USERNAME:root}
        password: ${SPRING_CART_DATASOURCE_PASSWORD:password}
        hikari:
            schema: ${SPRING_CART_DATASOURCE_SCHEME:cart}

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

    mvc:
        log-request-details: true



logging:
    level:
        web: trace
        org:
            springframework:
                web: trace

server:
    port: 8093
    servlet:
        context-path: ${EMAZON_CART_CONTEXT_PATH:/emazon/cart}

allowed-origins:
    http://localhost:3000/,
    *,

emazon:
    user:
        base-url: localhost:8090/emazon/user
    stock:
        base-url: localhost:8091/emazon/stock
    transaction:
        base-url: localhost:8092/emazon/transaction
    report:
        base-url: localhost:8094/emazon/report
